packages:
  - apps/*
  - packages/*
  - packages/course-app/src/*
onlyBuiltDependencies:
  - esbuild
  - '@tailwindcss/oxide'
patchedDependencies:
  layerchart@2.0.0-next.27: patches/layerchart@2.0.0-next.27.patch
overrides:
  zod: ^4.1.8
  miniflare>zod: 3.22.3
